version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}
    prom1: {}

services:

  grafana:
    image: grafana/grafana
    user: "472"
#    environment:
#        GF_SECURITY_ADMIN_USER: $GRAFANA_ADMIN_USER
#        GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASSWORD
#      GF_PATHS_PLUGINS='/var/lib/grafana/plugins' \
#      GF_PATHS_PROVISIONING='/etc/grafana/provisioning' \
#      GF_PATHS_DATA='/var/lib/grafana' \
#      GF_PATHS_LOGS='/var/log/grafana'
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
#      - grafana-storage:/var/lib/grafana
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
#	grafana-storage:

    env_file:
      - ./grafana/config.monitoring

#    networks:
#     internal:




  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus/
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
#    networks:
#        internal:



  cadvisor:
    hostname: cadvisor
    image: google/cadvisor:v0.33.0
    privileged: true
    volumes:
#      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    ports:
      - 8080:8080
    deploy:
      mode: global
#    networks:
#        internal:

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    deploy:
      mode: global
