{
 "title": "dash Copy",
 "description": "Postgresql Monitoring with Elasticsearch and PostgreSQL data sources",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"agent.hostname\"}"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "{\"find\": \"terms\", \"field\": \"postgresql.database.name\",\"query\": \"host.hostname:$host\" , \"postgresql.database.name\":\"a* to z*\" }"
   },
   {
    "name": "user",
    "label": "User",
    "query": "{\"find\": \"terms\", \"field\": \"postgresql.activity.user.name\", \"query\": \"host.hostname:$host\"}"
   }
  ]
 },
 "panels": [
  { "title": "System Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Info",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Core Memory",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "Used Memory",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.used.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total Memory",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Core Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.cores",
       "id": "1",
       "inlineScript": "_value",
       "meta": {},
       "settings": { "script": { "inline": "_value" } },
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.uptime.duration.ms",
       "id": "1",
       "inlineScript": "_value",
       "meta": {},
       "settings": { "script": { "inline": "_value" } },
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Root disk usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "inlineScript": "_value * 100",
       "meta": {},
       "settings": { "script": { "inline": "_value * 100" } },
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host AND system.filesystem.device_name:*root*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " /pgdata disk usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "inlineScript": "_value * 100",
       "meta": {},
       "settings": { "script": { "inline": "_value * 100" } },
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host AND system.filesystem.device_name:*pgdata*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "/backup disk usage ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "inlineScript": "_value * 100",
       "meta": {},
       "settings": { "script": { "inline": "_value * 100" } },
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host AND system.filesystem.device_name:*backup*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "/nfsbackup disk usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "inlineScript": "_value * 100",
       "meta": {},
       "settings": { "script": { "inline": "_value * 100" } },
       "type": "avg"
      }
     ],
     "query": "host.hostname: pg2 AND system.filesystem.mount_point:*nfsbackup*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "/pgdata_fb disk usage (pg3)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "inlineScript": "_value * 100",
       "meta": {},
       "settings": { "script": { "inline": "_value * 100" } },
       "type": "avg"
      }
     ],
     "query": "host.hostname: pg3 AND system.filesystem.mount_point:*pgdata_fb*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SWAP Info",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Used SWAP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.swap.used.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "Free SWAP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.swap.free",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total SWAP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.swap.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SWAP Info History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used SWAP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.swap.used.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage other than IOWait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage Detail ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "nice",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-70s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.cpu.nice.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "kernel system",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.cpu.system.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "user",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.cpu.user.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "softirq",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.cpu.softirq.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "steal",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.cpu.steal.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DISK I/O Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read per sec",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.diskio.iostat.read.per_sec.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "Write per sec",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.diskio.iostat.write.per_sec.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU  Time Percent wait on disk (iowait)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.iowait.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk I/O Usage Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "total milliseconds spent doing I/Os.",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.diskio.io.time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DISK IOps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.diskio.iostat.read.request.per_sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "Write",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.diskio.iostat.write.request.per_sec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Drop/Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "IN DROPPED",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-70s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.network.in.dropped",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.hostname:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "OUT DROPPED",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-70s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.network.out.dropped",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.hostname:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "IN ERROR",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-70s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.ne",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.hostname:$host",
     "timeField": "@timestamp"
    },
    {
     "alias": "OUT ERROR",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-70s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.network.out.errors",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.hostname:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    },
    {
     "alias": "Outbound",
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.hostname: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DB General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Delay",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\ntime_diff_sn AS pg1\nFROM\n  grafana.oksijen_replication\nWHERE\nstandby_name = 'pg1.domain.com'\n"
      },
      {
       "rawSql": "SELECT\ntime_diff_sn AS pg3\nFROM\n  grafana.oksijen_replication\nWHERE\nstandby_name = 'pg3.domain.com'\n"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 7, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n percentage as \"$database\"\nFROM grafana.cache_hit_ratio\nWHERE host = '$host' and\ndatabase = $database\n"
      }
     ]
    },
    {
     "title": "Cluster-Based Cache Hit Ratio ",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n avg(percentage) AS \"cluster-based value\"\nFROM grafana.cache_hit_ratio\nWHERE host = '$host'\n\n"
      }
     ]
    },
    {
     "title": "Dead Locks",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 11, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "postgresql.database.deadlocks",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Cluster Size",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 13, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1m", "min_doc_count": 0, "offset": "-2m", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "system.filesystem.used.bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "host.hostname: pg1 AND system.filesystem.mount_point: *pgdata*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "PG Version",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nversion as \"OKSIJEN\"\nFROM\n  grafana.server_version\nWHERE\nhost like 'oksijen%'"
      }
     ]
    },
    {
     "title": "Database Client Connection",
     "type": "briangann-gauge-panel",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 2 },
     "format": "none",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "15s", "min_doc_count": 0, "offset": "-17s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.activity.client.address",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user AND postgresql.activity.state: *",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Cluster Client Connection",
     "type": "briangann-gauge-panel",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 2 },
     "format": "none",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-17s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.activity.client.address",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "host.hostname: $host AND postgresql.activity.state: *",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Postgresql Event Duration Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "alias": "Average Event Duration",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "event.duration",
         "id": "1",
         "inlineScript": "_value / 100000",
         "meta": {},
         "settings": { "script": { "inline": "_value / 100000" } },
         "type": "avg"
        }
       ],
       "query": "service.type: postgresql AND host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Active Connection",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user AND postgresql.activity.state: \"active\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "Idle Connection",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user AND postgresql.activity.state: \"idle\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "Idle in Transaction Connection",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user AND postgresql.activity.state: \"idle in transaction\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "Idle in Transaction (Aborted) Connection",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user AND postgresql.activity.state: \"idle in transaction (aborted)\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "Empty Connection",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user AND postgresql.activity.state: \"\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "Disabled Connection",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user AND postgresql.activity.state: \"disabled\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "fastpath function call",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "host.hostname: $host AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user AND postgresql.activity.state: \"fastpath function call\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "UPDATE - DELETE - INSERT OPERATIONS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "INSERT",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "postgresql.database.rows.inserted",
         "hide": true,
         "id": "1",
         "inlineScript": "_value/10",
         "meta": {},
         "settings": { "script": { "inline": "_value/10" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      },
      {
       "alias": "DELETE",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "postgresql.database.rows.deleted",
         "hide": true,
         "id": "1",
         "inlineScript": "_value/10",
         "meta": {},
         "settings": { "script": { "inline": "_value/10" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      },
      {
       "alias": "UPDATE",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "postgresql.database.rows.updated",
         "hide": true,
         "id": "1",
         "inlineScript": "_value/10",
         "meta": {},
         "settings": { "script": { "inline": "_value/10" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Blocks Hit / Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "Block Hit",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.database.blocks.hit",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / 8192",
         "meta": {},
         "settings": { "script": { "inline": "_value / 8192" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      },
      {
       "alias": "Block Read",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.database.blocks.read",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / 8192",
         "meta": {},
         "settings": { "script": { "inline": "_value / 8192" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Database Rows Fetched",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Rows Fetched",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.database.rows.fetched",
         "hide": true,
         "id": "1",
         "inlineScript": "_value",
         "meta": {},
         "settings": { "script": { "inline": "_value" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Commit / Rollback Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Rollback Transactions",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.database.transactions.rollback",
         "hide": true,
         "id": "1",
         "inlineScript": "_value/10",
         "meta": {},
         "settings": { "script": { "inline": "_value/10" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      },
      {
       "alias": "Commit Transactions",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.database.transactions.commit",
         "hide": true,
         "id": "1",
         "inlineScript": "_value/10",
         "meta": {},
         "settings": { "script": { "inline": "_value/10" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Database Rows Returned",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Rows Returned",
       "bucketAggs": [
        {
         "fake": true,
         "field": "@timestamp",
         "id": "3",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.database.rows.returned",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "4",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Number of Temp Files",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Temp file count",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.database.temporary.files",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "sum"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Size of Temp Files",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "alias": "Temp files size",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.database.temporary.bytes",
         "hide": true,
         "id": "1",
         "inlineScript": "_value / 1073741824",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": { "script": { "inline": "_value / 1073741824" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host AND postgresql.database.name: $database",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Written during checkpoint",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.bgwriter.buffers.checkpoints",
         "hide": true,
         "id": "1",
         "inlineScript": "_value * 8192",
         "meta": {},
         "settings": { "script": { "inline": "_value * 8192" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host",
       "timeField": "@timestamp"
      },
      {
       "alias": "Allocated",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.bgwriter.buffers.allocated",
         "hide": true,
         "id": "1",
         "inlineScript": "_value * 8192",
         "meta": {},
         "settings": { "script": { "inline": "_value * 8192" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host",
       "timeField": "@timestamp"
      },
      {
       "alias": "written directly by a backend.",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.bgwriter.buffers.backend",
         "hide": true,
         "id": "1",
         "inlineScript": "_value * 8192",
         "meta": {},
         "settings": { "script": { "inline": "_value * 8192" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host",
       "timeField": "@timestamp"
      },
      {
       "alias": "bgwriter.buffers.clean",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "postgresql.bgwriter.buffers.clean",
         "hide": true,
         "id": "1",
         "inlineScript": "_value * 8192",
         "meta": {},
         "settings": { "script": { "inline": "_value * 8192" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host",
       "timeField": "@timestamp"
      },
      {
       "alias": "Fsync calls by a backend",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "postgresql.bgwriter.buffers.backend_fsync",
         "hide": true,
         "id": "1",
         "inlineScript": "_value * 8192",
         "meta": {},
         "settings": { "script": { "inline": "_value * 8192" } },
         "type": "avg"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "host.hostname: $host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Postgresql with Application Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "postgresql.activity.application_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "10s", "min_doc_count": 0, "offset": "-15s", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "service.type: postgresql AND host.hostname: oksijen* AND postgresql.activity.database.name: $database AND postgresql.activity.user.name: $user",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Table Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Vacuum Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n--host AS \"Hostname\",\ndatabase AS \"Database\",\nschemaname AS \"Schema\",\ntablename AS \"Table\",\nlive_tuple AS \"Live Tuples\",\ndead_tuple AS \"Dead Tuples\",\n((dead_tuple/(live_tuple+dead_tuple)::float)*100)::int AS \"Dead Percentage%\",\nto_char(last_autovacuum, 'YYYY-MM-DD HH24:MI:SS' ) AS \"Last Autovacuum Date\"\nFROM\n  grafana.deadtuplestat\nWHERE \nhost like 'oksijen%'\n--database = $database \nAND \nschemaname NOT LIKE 'pg%' "
      }
     ]
    },
    {
     "title": "Table Size Info",
     "type": "table",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\ndatabase AS \"Database\",\nschema_name AS \"Schema\",\ntable_name AS \"Table\",\npg_size_pretty(table_size) AS \"Size in GB\"\n\nFROM\n  grafana.table_size\nWHERE \nhost like 'oksijen%'\nAND\n--database = $database \n--AND \nschema_name NOT LIKE 'pg%' \nORDER BY table_size DESC"
      }
     ]
    }
   ]
  }
 ]
}